### ISSUE TITLE
网站问题

### ISSUE THREAD

**Issue by NEWPLAN** [DjangoPeng/DjangoPeng.github.io#1]
大佬，你的网站被黑掉了。

**Comment by DjangoPeng** [comment]
谢谢您的关注！
网站的CNAME是zjupjt.com，这个域名到期了，我刚刚删掉了CNAME文件，现在应该可以访问了。
网址是：djangopeng.github.io

BTW:之前在华为，所有工作产出都在华为内网上，因此没有再维护和更新个人网站。近期我会重新开始维护个人网站。

**Comment by NEWPLAN** [comment]
哈哈，活跃在github的技术达人，刚刚试了一下，发现还是有点问题，重定向到http://www.hf193.com/了。。。不知道是不是有意为止。
同时发现，你原来也是12级本科，说来惭愧，同一年读的本科，差距如此之大。。。哈哈哈
看到您在tensorflow的贡献，我最近也在做实验，需要修改其中的分布式结构，发现理解不到，有点困难，不知是否可以和您咨询呢？？？

**Comment by DjangoPeng** [comment]
我这里访问是正常的，不过有点慢。你是不是被DNS劫持了？
